apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-api.fullname" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "spring-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spring-api.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spring-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.externalSecret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecret.targetSecretName }}
          {{- end }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.probes.port }}
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
