{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "spring-api.fullname" . }}-external-secret
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteSecretName | quote }}
        property: {{ .property | quote }}
    {{- end }}
{{- end }}
