{{- if and .Values.awsSecretsAccess.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.awsSecretsAccess.serviceAccountName }}
{{- end }}
