apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-api
  namespace: argocd
spec:
  description: Spring API GitOps project
  sourceRepos:
    - 'https://github.com/Sangram-Rajpoot/backend-app-repo.git'
  destinations:
    - namespace: spring-api
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
