replicaCount: 2

image:
  repository: https://jfrogtrial2166.jfrog.io/artifactory/api/docker/docker-local
  tag: set-by-jenkins
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: jfrog-regcred

serviceAccount:
  create: true
  name: ""

externalSecret:
  enabled: false

awsSecretsAccess:
  enabled: false
# awsSecretsAccess:
#   enabled: true
#   serviceAccountName: aws-secrets-reader
#   roleArn: arn:aws:iam::123456789012:role/spring-api-secrets-reader

# secretStore:
#   name: aws-secretsmanager
#   region: ap-south-1

externalSecret:
  enabled: true
  refreshInterval: 1h
  targetSecretName: spring-api-env
  remoteSecretName: prod/spring-api
  data:
    - secretKey: SPRING_PROFILES_ACTIVE
      property: spring_profiles_active
    - secretKey: DB_URL
      property: db_url
    - secretKey: DB_USERNAME
      property: db_username
    - secretKey: DB_PASSWORD
      property: db_password
    - secretKey: APP_FEATURE_FLAG
      property: app_feature_flag

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

probes:
  port: 8080
  livenessPath: /livez
  readinessPath: /readyz

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1
