image:
  repository: https://jfrogtrial2166.jfrog.io/artifactory/api/docker/docker-local
  tag: set-by-jenkins

awsSecretsAccess:
  roleArn: arn:aws:iam::123456789012:role/spring-api-secrets-reader

secretStore:
  region: ap-south-1
