image:
  repository: https://jfrogtrial2166.jfrog.io/artifactory/api/docker/docker-local
  tag: set-by-jenkins
  
externalSecret:
  enabled: false

awsSecretsAccess:
  enabled: false

secretStore:
  region: ap-south-1

